fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: [ --maxkb=10000 ]
    -   id: debug-statements
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
        language_version: python3

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.265"
    hooks:
    -   id: ruff

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: []

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
